on: 
  pull_request:
    branches:
      - master
name: Terraform
jobs:
  filter-to-pr-open-synced:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: terraform-fmt
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: terraform-init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: terraform-validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: terraform-plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
